#!/usr/bin/env bash

########################################################
###                        Help                      ###
########################################################

HELP='
Application process actions.

Usage:

    application [action]

Parameters:

    * action

        Application process actions.

        - start              Start the application.
'

########################################################
###                     Variables                    ###
########################################################

# Node environment
if [[ -z $NODE_ENV ]]; then
    NODE_ENV='development'
fi

# Node
NODE='node'

########################################################
###                      Export                      ###
########################################################

# Node config directory
export NODE_CONFIG_DIR="$PWD/configs/node"

########################################################
###                      Helpers                     ###
########################################################

#
# Print a title of action
#
# @1 {string} Title
#
printTitle() {
    echo "===> $1"
}

########################################################
###                     Actions                      ###
########################################################

#
# Help
#
help() {
    echo "$HELP"
}

#
# Start the application
#
start() {
    printTitle 'Running the application'

    echo "User:            $(whoami)"
    echo "Environment:     $NODE_ENV"
    echo "Nodejs version:  $("$NODE" --version)"

    "$NODE" index
}

########################################################
###                    Call action                   ###
########################################################

case "$1" in
    start)
        "$1"
    ;;
    *)
        help
    ;;
esac
