#!/usr/bin/env bash

########################################################
###                        Help                      ###
########################################################

HELP='
Deploy config actions.

Usage:

    deploy-config [action]

Parameters:

    * action

        Deploy config actions.

        - nginx    Deploy the nginx config.
'

########################################################
###                     Variables                    ###
########################################################

# Project name
if [[ -z $PROJECT_NAME ]]; then
    PROJECT_NAME=$(jq -r '.name' package.json)
fi

# Node directories
NODE_BIN_DIR=(
    '/usr/bin'
    '/usr/local/bin'
)

# Node
NODE=$(find "${NODE_BIN_DIR[@]}" -name 'node' \( -type f -o -type l \))

# Node modules directory
NODE_MODULES_DIR='node_modules'

# Configs directory
CONFIGS_DIR="$PWD/configs"

# Nginx directory
NGINX_DIR="/etc/nginx"

########################################################
###                      Export                      ###
########################################################

# Node config directory
export NODE_CONFIG_DIR="$CONFIGS_DIR/node"

########################################################
###                      Helpers                     ###
########################################################

#
# Print a title of action
#
# @1 {string} Title
#
print_title() {
    echo "===> $1"
}

########################################################
###                     Actions                      ###
########################################################

#
# Help
#
help() {
    echo "$HELP"
}

#
# Start the application
#
nginx() {
    print_title 'Deploy nginx config'

    "$NODE" replace-vars.js \
        "$NODE_MODULES_DIR"/app-core/configs/nginx/base.conf \
        "$CONFIGS_DIR"/nginx/vars.js \
        > "$NGINX_DIR"/sites-available/"$PROJECT_NAME"

    ln -sfn \
        "$NGINX_DIR"/sites-available/"$PROJECT_NAME" \
        "$NGINX_DIR"/sites-enabled/"$PROJECT_NAME"
}

########################################################
###                    Call action                   ###
########################################################

case "$1" in
    nginx)
        "$1"
    ;;
    *)
        help
    ;;
esac
