#
#    Application:
#
#    		start		Start an application
#

########################################################
###                     Variables                    ###
########################################################

# Scripts directory
SCRIPTS_DIR := @ . node_modules/app-core/tools/scripts

# Application script
SCRIPT_APP := $(SCRIPTS_DIR)/application

########################################################
###                Application rules                 ###
########################################################

# Start an application
.PHONY: start
start:
	$(SCRIPT_APP) startDev
